#!/bin/bash
CurrentDate=$(date +%Y-%m-%d)
# ======================================
# get gfwlist for shadowsocks ipset mode

# https://github.com/u20024804/gfwlist2dnsmasq
# temporary file
temporary_file=$(mktemp) || temporary_file='domain_list.txt'

# convert gfwlist.txt
#baseurl='https://raw.githubusercontent.com/Loukky/gfwlist-by-loukky/master/gfwlist.txt'
baseurl='https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt'

curl -4sSkL ${baseurl} | base64 -d | { perl -pe '
if (/URL Keywords/i) { $null = <> until $null =~ /^!/ }
s#^\s*+$|^!.*+$|^@@.*+$|^\[AutoProxy.*+$|^/.*/$##i;
s@^\|\|?|\|$@@;
s@^https?:/?/?@@i;
s@(?:/|%).*+$@@;
s@\*[^.*]++$@\n@;
s@^.*?\*[^.]*+(?=[^*]+$)@@;
s@^\*?\.|^.*\.\*?$@@;
s@(?=[^0-9a-zA-Z.-]).*+$@@;
s@^\d+\.\d+\.\d+\.\d+(?::\d+)?$@@;
s@^\s*+$@@'
echo 'twimg.edgesuite.net'
echo -e 'huobi.be\nbintray.com\nv2ex.com\ngradle.org\nplugins.jetbrains.com'
echo -e 'github.io\napi.github.com\ngithubapp.com\nraw.githubusercontent.com\navatars.githubusercontent.com\nuser-images.githubusercontent.com'
echo -e 'blogspot.ae\nblogspot.al\nblogspot.am\nblogspot.ba\nblogspot.be\nblogspot.bg\nblogspot.bj\nblogspot.ca\nblogspot.cat\nblogspot.cf\nblogspot.ch\nblogspot.cl\nblogspot.co.at\nblogspot.co.id\nblogspot.co.il\nblogspot.co.ke\nblogspot.com\nblogspot.com.ar\nblogspot.com.au\nblogspot.com.br\nblogspot.com.by\nblogspot.com.co\nblogspot.com.cy\nblogspot.com.ee\nblogspot.com.eg\nblogspot.com.es\nblogspot.com.mt\nblogspot.com.ng\nblogspot.com.tr\nblogspot.com.uy\nblogspot.co.nz\nblogspot.co.uk\nblogspot.co.za\nblogspot.cv\nblogspot.cz\nblogspot.de\nblogspot.dk\nblogspot.fi\nblogspot.fr\nblogspot.gr\nblogspot.hk\nblogspot.hr\nblogspot.hu\nblogspot.ie\nblogspot.in\nblogspot.is\nblogspot.it\nblogspot.jp\nblogspot.kr\nblogspot.li\nblogspot.lt\nblogspot.lu\nblogspot.md\nblogspot.mk\nblogspot.mr\nblogspot.mx\nblogspot.my\nblogspot.nl\nblogspot.no\nblogspot.pe\nblogspot.pt\nblogspot.qa\nblogspot.re\nblogspot.ro\nblogspot.rs\nblogspot.ru\nblogspot.se\nblogspot.sg\nblogspot.si\nblogspot.sk\nblogspot.sn\nblogspot.td\nblogspot.tw\nblogspot.ug\nblogspot.vn'
echo -e 'www.google.com\ngoogle.ac\ngoogle.ad\ngoogle.ae\ngoogle.al\ngoogle.am\ngoogle.as\ngoogle.at\ngoogle.az\ngoogle.ba\ngoogle.be\ngoogle.bf\ngoogle.bg\ngoogle.bi\ngoogle.bj\ngoogle.bs\ngoogle.bt\ngoogle.by\ngoogle.ca\ngoogle.cat\ngoogle.cc\ngoogle.cd\ngoogle.cf\ngoogle.cg\ngoogle.ch\ngoogle.ci\ngoogle.cl\ngoogle.cm\ngoogle.cn\ngoogle.co.ao\ngoogle.co.bw\ngoogle.co.ck\ngoogle.co.cr\ngoogle.co.id\ngoogle.co.il\ngoogle.co.in\ngoogle.co.jp\ngoogle.co.ke\ngoogle.co.kr\ngoogle.co.ls\ngoogle.com\ngoogle.co.ma\ngoogle.com.af\ngoogle.com.ag\ngoogle.com.ai\ngoogle.com.ar\ngoogle.com.au\ngoogle.com.bd\ngoogle.com.bh\ngoogle.com.bn\ngoogle.com.bo\ngoogle.com.br\ngoogle.com.bz\ngoogle.com.co\ngoogle.com.cu\ngoogle.com.cy\ngoogle.com.do\ngoogle.com.ec\ngoogle.com.eg\ngoogle.com.et\ngoogle.com.fj\ngoogle.com.gh\ngoogle.com.gi\ngoogle.com.gt\ngoogle.com.hk\ngoogle.com.jm\ngoogle.com.kh\ngoogle.com.kw\ngoogle.com.lb\ngoogle.com.lc\ngoogle.com.ly\ngoogle.com.mm\ngoogle.com.mt\ngoogle.com.mx\ngoogle.com.my\ngoogle.com.na\ngoogle.com.nf\ngoogle.com.ng\ngoogle.com.ni\ngoogle.com.np\ngoogle.com.om\ngoogle.com.pa\ngoogle.com.pe\ngoogle.com.pg\ngoogle.com.ph\ngoogle.com.pk\ngoogle.com.pr\ngoogle.com.py\ngoogle.com.qa\ngoogle.com.sa\ngoogle.com.sb\ngoogle.com.sg\ngoogle.com.sl\ngoogle.com.sv\ngoogle.com.tj\ngoogle.com.tr\ngoogle.com.tw\ngoogle.com.ua\ngoogle.com.uy\ngoogle.com.vc\ngoogle.com.vn\ngoogle.co.mz\ngoogle.co.nz\ngoogle.co.th\ngoogle.co.tz\ngoogle.co.ug\ngoogle.co.uk\ngoogle.co.uz\ngoogle.co.ve\ngoogle.co.vi\ngoogle.co.za\ngoogle.co.zm\ngoogle.co.zw\ngoogle.cv\ngoogle.cz\ngoogle.de\ngoogle.dj\ngoogle.dk\ngoogle.dm\ngoogle.dz\ngoogle.ee\ngoogle.es\ngoogle.fi\ngoogle.fm\ngoogle.fr\ngoogle.ga\ngoogle.ge\ngoogle.gf\ngoogle.gg\ngoogle.gl\ngoogle.gm\ngoogle.gp\ngoogle.gr\ngoogle.gy\ngoogle.hn\ngoogle.hr\ngoogle.ht\ngoogle.hu\ngoogle.ie\ngoogle.im\ngoogle.io\ngoogle.iq\ngoogle.is\ngoogle.it\ngoogle.je\ngoogle.jo\ngoogle.kg\ngoogle.ki\ngoogle.kz\ngoogle.la\ngoogle.li\ngoogle.lk\ngoogle.lt\ngoogle.lu\ngoogle.lv\ngoogle.md\ngoogle.me\ngoogle.mg\ngoogle.mk\ngoogle.ml\ngoogle.mn\ngoogle.ms\ngoogle.mu\ngoogle.mv\ngoogle.mw\ngoogle.ne\ngoogle.net\ngoogle.nl\ngoogle.no\ngoogle.nr\ngoogle.nu\ngoogle.org\ngoogle.pl\ngoogle.pn\ngoogle.ps\ngoogle.pt\ngoogle.ro\ngoogle.rs\ngoogle.ru\ngoogle.rw\ngoogle.sc\ngoogle.se\ngoogle.sh\ngoogle.si\ngoogle.sk\ngoogle.sm\ngoogle.sn\ngoogle.so\ngoogle.sr\ngoogle.st\ngoogle.td\ngoogle.tg\ngoogle.tk\ngoogle.tl\ngoogle.tm\ngoogle.tn\ngoogle.to\ngoogle.tt\ngoogle.vg\ngoogle.vu\ngoogle.ws'; } | sort | uniq -i >${temporary_file}

# generated file type
test -z "$dns_addr" && dns_addr='127.0.0.1'
test -z "$dns_port" && dns_port='7913'
echo "# Generated by gfwlist2dnsmasq at $(date '+%F %T')" >gfwlist_download.conf
perl -pe "s@^.*+\$@server=/.$&/$dns_addr#$dns_port\nipset=/.$&/gfwlist@" ${temporary_file} >>gfwlist_download.conf
# perl -pe "s@^.*+\$@server=/.$&/$dns_addr#$dns_port@" ${temporary_file} >>dnsmasq_gfwlist.conf
rm -fr ${temporary_file}
echo "type: dnsmasq_ipset     file: gfwlist_download.conf"

sort -k 2 -t. -u gfwlist_download.conf >gfwlist1.conf

# delete site below
sed -i '/m-team/d' "gfwlist1.conf"
sed -i '/windowsupdate/d' "gfwlist1.conf"
sed -i '/v2ex/d' "gfwlist1.conf"
sed -i '/apple\.com/d' "gfwlist1.conf"

md5sum1=$(md5sum gfwlist1.conf | sed 's/ /\n/g' | sed -n 1p)
md5sum2=$(md5sum ../gfwlist.conf | sed 's/ /\n/g' | sed -n 1p)

echo =================
if [ "$md5sum1"x = "$md5sum2"x ]; then
	echo gfwlist same md5!
else
	echo update gfwlist!
	cp -f gfwlist1.conf ../gfwlist.conf
	sed -i "1c $(date +%Y-%m-%d) # $md5sum1 gfwlist" ../version.sum
fi
echo =================
# ======================================
# get chnroute for shadowsocks chn and game mode

# Deprecated in 2019-8-1
# wget -4 -O- http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest > apnic.txt
# cat apnic.txt| awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute1.txt

# use ipip_country_cn ip database sync by https://github.com/firehol/blocklist-ipsets from ipip.net（source: https://cdn.ipip.net/17mon/country.zip）.
curl -fSL https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/ipip_country/ipip_country_cn.netset | sed '/^#/d' >chnroute1.txt

md5sum3=$(md5sum chnroute1.txt | sed 's/ /\n/g' | sed -n 1p)
md5sum4=$(md5sum ../chnroute.txt | sed 's/ /\n/g' | sed -n 1p)

echo =================
if [ "$md5sum3"x = "$md5sum4"x ]; then
	echo chnroute same md5!
else
	IPLINE=$(cat chnroute1.txt | wc -l)
	IPCOUN=$(awk -F "/" '{sum += 2^(32-$2)-2};END {print sum}' chnroute1.txt)
	echo update chnroute, $IPLINE subnets, $IPCOUN unique IPs !
	cp -f chnroute1.txt ../chnroute.txt
	sed -i "2c $(date +%Y-%m-%d) # $md5sum3 chnroute" ../version.sum
fi
echo =================
# ======================================
# get cdn list for shadowsocks chn and game mode

curl -fSLO https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
curl -fSLO https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
curl -fSLO https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf

cat accelerated-domains.china.conf apple.china.conf google.china.conf | sed '/^#/d' | sed "s/server=\/\.//g" | sed "s/server=\///g" | sed -r "s/\/\S{1,30}//g" | sed -r "s/\/\S{1,30}//g" >cdn_download.txt
cat cdn_koolshare.txt cdn_custom.txt cdn_download.txt| sort -u >cdn1.txt

md5sum5=$(md5sum cdn1.txt | sed 's/ /\n/g' | sed -n 1p)
md5sum6=$(md5sum ../cdn.txt | sed 's/ /\n/g' | sed -n 1p)

echo =================
if [ "$md5sum5"x = "$md5sum6"x ]; then
	echo cdn list same md5!
else
	echo update cdn!
	cp -f cdn1.txt ../cdn.txt
	sed -i "4c $(date +%Y-%m-%d) # $md5sum5 cdn" ../version.sum
fi
echo =================
echo "use apnic data"
# ======================================
# use apnic data
curl -fSL http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest >apnic.txt
cat apnic.txt | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' >chnroute1.txt

echo -e "[Local Routing]\n## China mainland routing blocks\n## Sources: https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest" >Routing.txt
echo -n "## Last update: " >>Routing.txt
echo $CurrentDate >>Routing.txt
echo -e "\n" >>Routing.txt

# IPv4
echo "## IPv4" >>Routing.txt
cat apnic.txt | grep ipv4 | grep CN | awk -F\| '{printf("%s/%d\n", $4, 32-log($5)/log(2))}' >>Routing.txt
echo -e "\n" >>Routing.txt

# IPv6
echo "## IPv6" >>Routing.txt
cat apnic.txt | grep ipv6 | grep CN | awk -F\| '{printf("%s/%d\n", $4, $5)}' >>Routing.txt

[ ! -f "../Routing.txt" ] && cp Routing.txt ..

md5sum9=$(md5sum Routing.txt | sed 's/ /\n/g' | sed -n 1p)
md5sum10=$(md5sum ../Routing.txt | sed 's/ /\n/g' | sed -n 1p)
echo =================
if [ "$md5sum9"x = "$md5sum10"x ]; then
	echo Routing same md5!
else
	echo update Routing!
	cp Routing.txt ..
	sed -i "5c $(date +%Y-%m-%d) # $md5sum9 Routing" ../version.sum
fi
echo =================
# ======================================
sed 's|/114.114.114.114$||' accelerated-domains.china.conf >WhiteList_tmp.txt
sed -i 's|\(\.\)|\\\1|g' WhiteList_tmp.txt
sed -i 's|server=/|.*\\\b|' WhiteList_tmp.txt
sed -i 's|b\(cn\)$|\.\1|' WhiteList_tmp.txt

echo '[Local Hosts]' >>WhiteList.txt
echo '## China mainland domains' >>WhiteList.txt
echo '## Get the latest database: https://github.com/xinhugo/Free-List/blob/master/WhiteList.txt' >>WhiteList.txt
echo '## Report an issue: https://github.com/xinhugo/Free-List/issues' >>WhiteList.txt
echo -e "## Last update: $CurrentDate\n" >>WhiteList.txt
cat WhiteList_tmp.txt >>WhiteList.txt

[ ! -f "../WhiteList.txt" ] && mv WhiteList_tmp.txt >>WhiteList.txt

md5sum7=$(md5sum WhiteList.txt | sed 's/ /\n/g' | sed -n 1p)
md5sum8=$(md5sum ../WhiteList.txt | sed 's/ /\n/g' | sed -n 1p)
echo =================
if [ "$md5sum7"x = "$md5sum8"x ]; then
	echo WhiteList same md5!
else
	echo update WhiteList!
	cp -f WhiteList.txt ../WhiteList.txt
	sed -i "6c $(date +%Y-%m-%d) # $md5sum7 WhiteList" ../version.sum
fi
echo =================

# ======================================
echo -e "[Local Hosts]\n## China mainland domains\n## Source: https://github.com/felixonmars/dnsmasq-china-list" >WhiteList_new.txt
echo -n "## Last update: " >>WhiteList_new.txt
echo $CurrentDate >>WhiteList_new.txt
echo -e "\n" >>WhiteList_new.txt
sed -e "s|114.114.114.114$||" -e "s|^s|S|" accelerated-domains.china.conf >>WhiteList_new.txt

# Download domain data of Google in Mainland China part.
#curl -O https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
sed -e "s|114.114.114.114$||" -e "s|^s|S|" google.china.conf >>WhiteList_new.txt

# Download domain data of Apple in Mainland China part.
#curl -O https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
sed -e "s|114.114.114.114$||" -e "s|^s|S|" apple.china.conf >>WhiteList_new.txt

# ok
[ ! -f "../WhiteList_new.txt" ] && cp WhiteList_new.txt ..

md5sum11=$(md5sum WhiteList_new.txt | sed 's/ /\n/g' | sed -n 1p)
md5sum12=$(md5sum ../WhiteList_new.txt | sed 's/ /\n/g' | sed -n 1p)
echo =================
if [ "$md5sum11"x = "$md5sum12"x ]; then
	echo WhiteList_new same md5!
else
	echo update WhiteList_new!
	cp WhiteList_new.txt ..
	sed -i "7c $(date +%Y-%m-%d) # $md5sum11 WhiteList_new" ../version.sum
fi
echo =================

# ======================================
# get cdn list for shadowsocks chn and game mode
cat apple.china.conf | sed '/^#/d' | sed "s/server=\/\.//g" | sed "s/server=\///g" | sed -r "s/\/\S{1,30}//g" | sed -r "s/\/\S{1,30}//g" | sort -u > apple_download.txt
cat google.china.conf | sed '/^#/d' | sed "s/server=\/\.//g" | sed "s/server=\///g" | sed -r "s/\/\S{1,30}//g" | sed -r "s/\/\S{1,30}//g" | sort -u > google_download.txt

md5sum13=$(md5sum apple_download.txt | sed 's/ /\n/g' | sed -n 1p)
md5sum14=$(md5sum ../apple_china.txt | sed 's/ /\n/g' | sed -n 1p)

md5sum15=$(md5sum google_download.txt | sed 's/ /\n/g' | sed -n 1p)
md5sum16=$(md5sum ../google_china.txt | sed 's/ /\n/g' | sed -n 1p)

echo =================
if [ "$md5sum13"x = "$md5sum14"x ]; then
	echo apple china list same md5!
else
	echo update apple china list!
	cp -f apple_download.txt ../apple_china.txt
	sed -i "8c $(date +%Y-%m-%d) # $md5sum13 apple_china" ../version.sum
fi
if [ "$md5sum15"x = "$md5sum16"x ]; then
	echo google china list same md5!
else
	echo update goole china list!
	cp -f google_download.txt ../google_china.txt
	sed -i "9c $(date +%Y-%m-%d) # $md5sum15 google_china" ../version.sum
fi
echo =================
# ======================================
rm google.china.conf
rm apple.china.conf
rm gfwlist1.conf gfwlist_download.conf chnroute1.txt
rm cdn1.txt accelerated-domains.china.conf cdn_download.txt apple_download.txt google_download.txt
rm WhiteList.txt WhiteList_tmp.txt apnic.txt WhiteList_new.txt Routing.txt
